name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: install meson
      run: sudo apt install meson
    - name: install ncurses
      run: sudo apt install libncurses-dev
    - name: install postgres
      run: sudo apt install postgresql
    - name: configure
      run: meson build
    - name: build
      run: ninja -C build
